// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caategory = "Telefon",
                            Description = "Samusungun en iyi telefonu",
                            Name = "Samsung S24",
                            Price = 40000m
                        },
                        new
                        {
                            Id = 2,
                            Caategory = "Telefon",
                            Description = "Samusungun en iyi telefonu",
                            Name = "Samsung S25",
                            Price = 50000m
                        },
                        new
                        {
                            Id = 3,
                            Caategory = "Telefon",
                            Description = "Samusungun en iyi telefonu",
                            Name = "Samsung S26",
                            Price = 60000m
                        },
                        new
                        {
                            Id = 4,
                            Caategory = "Telefon",
                            Description = "Samusungun en iyi telefonu",
                            Name = "Samsung S27",
                            Price = 70000m
                        },
                        new
                        {
                            Id = 5,
                            Caategory = "Telefon",
                            Description = "Samusungun en iyi telefonu",
                            Name = "Samsung S28",
                            Price = 80000m
                        },
                        new
                        {
                            Id = 6,
                            Caategory = "Telefon",
                            Description = "Samusungun en iyi telefonu",
                            Name = "Samsung S29",
                            Price = 90000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
